### ISSUE TITLE
The LAMMPS dump information have a low probability will not be recognized correctly

### ISSUE THREAD

**Issue by bagayang** [irisTa56/ppap4lmp#13]
In my shear simulation case, when the dumps  likes this , the  velocity can not be recognize correctly.

> ITEM: BOX BOUNDS pp pp ff
> 0 43.6044
> 0 50.35
> 0 146.602
> ITEM: ATOMS id type xu yu zu vx vy vz 
> 4819 16 1.45348 -452.368 7.15727 0 -5e-05 0 
> 4021 15 4.35454 -502.68 8.79923 0.000942157 0.00101976 -0.00331828 

If the velocity in first line is not Integer, it is OK. 

I check the code in `sta_dump_atoms.cpp`.  I think the problem is that use the function `is_int_vector` divide the data into the wrong format. 

```
         Vec<bool> is_int_vector;
 
         for (const auto &s : ut::split(line))
         {
           // NOTE: If string containes '.', it is converted to float.
           is_int_vector.push_back(s.find(".") == Str::npos);
         }
```

**Comment by irisTa56** [comment]
Thank you for your feedback!
I'll take a look somewhere this week.
Or could you open a PR fixing the problem?

**Comment by bagayang** [comment]
My idea is to recognize the data forma by the name (id, type, xu, etc. ), it maybe not so efficient .
I'll try to write it into PR this week.

**Comment by irisTa56** [comment]
@bagayang 
I open https://github.com/irisTa56/ppap4lmp/pull/14.
Could you check if it works for your case?

**Comment by bagayang** [comment]
> @bagayang I open #14. Could you check if it works for your case?

I have checked it. It's OK. 
Sorry, I didn't check the email in time, replying so late. Thanks you very much.

**Comment by irisTa56** [comment]
Thank you for your confirmation!
